import { createClient } from "@supabase/supabase-js";
import { SignJWT } from "jose";
import { auth } from "../auth/server";

/**
 * Signs a JWT token using Supabase JWT secret for authenticated API access
 * @param payload - The user data to include in the JWT
 * @param userId - The user ID to include in the sub claim
 * @returns Promise<string> - The signed JWT token
 */
export async function signSupabaseJWT(
  payload: {
    id: string;
    email: string;
    role: string;
    [key: string]: any;
  },
  userId: string
): Promise<string> {
  const supabaseJwtSecret = process.env.SUPABASE_JWT_SECRET;

  if (!supabaseJwtSecret) {
    throw new Error("SUPABASE_JWT_SECRET environment variable is required");
  }

  const secret = new TextEncoder().encode(supabaseJwtSecret);

  // Create JWT payload following Supabase conventions
  const jwtPayload = {
    sub: userId,
    email: payload.email,
    user_metadata: {
      name: payload.name,
      email: payload.email,
    },
    app_metadata: {
      provider: "credentials",
      providers: ["credentials"],
    },
    aud: "authenticated",
    role: "authenticated",
    // Add custom claims for your application
    vendorId: payload.vendorId,
    staffId: payload.staffId,
    userRole: payload.role,
  };

  const jwt = await new SignJWT(jwtPayload)
    .setProtectedHeader({ alg: "HS256", typ: "JWT" })
    .setIssuedAt()
    .setExpirationTime("24h")
    .setIssuer(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/auth/v1`)
    .setAudience("authenticated")
    .sign(secret);

  return jwt;
}


/**
 * Creates an authenticated Supabase client for server-side use
 * Uses the sbToken from session (generated by customSession plugin)
 */
export async function getAuthenticatedSupabaseClient() {
  const session = await auth();

  if (!session) {
    throw new Error("No active session - user must be authenticated");
  }

  // Use sbToken from session (generated by customSession plugin)
  const sbToken = session.user.sbToken;

  if (!sbToken) {
    throw new Error("No sbToken in session");
  }

  // Create Supabase client with the JWT
  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      global: {
        headers: {
          Authorization: `Bearer ${sbToken}`,
        },
      },
      realtime: {
        params: {
          eventsPerSecond: 100,
        },
      },
    }
  );

  return supabase;
}

/**
 * Helper to get just the Supabase JWT without creating a client
 */
export async function getSupabaseJWT(): Promise<string> {
  const session = await auth();

  if (!session) {
    throw new Error("No active session");
  }

  const sbToken = session.user.sbToken;

  if (!sbToken) {
    throw new Error("No sbToken in session");
  }

  return sbToken;
}
